### PR TITLE
Update package to ES 1.2.1

### PR DESCRIPTION
**Pull request by electrical**
This should update the package to ES 1.2.1 but haven't been able to validate if the package works like expected.

### CODE REVIEW

**Comment by electrical** [comment]
Looks like that with ES 1.2.1 it doesn't want to start for some reason. see if i can do some digging.

**Comment by electrical** [comment]
Ah. found i was doing some things wrong ;-) first time ever using it.
This part so far works fine :-)

**Comment by stuartf** [comment]
Looks good, thanks

**Comment by electrical** [comment]
I've uploaded the new package as well. hope i done everything right :-)

**Pull request merged**
